### ISSUE TITLE
FR: TLS Support

### ISSUE THREAD

**Issue by stevenengland** [mib1185/ha-addon-syslog#8]
Hi there,

thanks for this addon. Is there a chance to get TLS support? I thinkt that there isn't because I get broken PIPE messages from the addon if I try to connect to the server.

**Comment by mib1185** [comment]
at the moment, there is only support for plain transmission via udp and tcp. there is an open feature request to the python standard lib, to add ssl support for [syslog handlers](https://discuss.python.org/t/allow-tls-configuration-for-sysloghandler/40785). maybe it is possible to integrate the community package for now, but need to check it further

**Comment by mib1185** [comment]
Hi @stevenengland 

i've added TLS support (_consider it to be experimental for now_) with [v0.3.0](https://github.com/mib1185/ha-addon-syslog/releases/tag/v0.3.0) which is available now. Please test if this works for you and don't hesitate to report any found issues, thx :+1:

**Comment by stevenengland** [comment]
Hi @mib1185 thank you for this fast implementation.

For now I tested it TLS and without cert check. It says it starts
```
[21:10:32] INFO: Set configuration...
[21:10:32] INFO: Starting the daemon...
```
but it does not log anything and does not bring any error in the hosts logs.

As fast as I switch back to UDP the logs come in again. I would need to investigate a little more but I cannot promise when this will happen...

**Comment by mib1185** [comment]
I've tested it successfully with the protocol center app on my Synology NAS.
Please try with enabled SSL verification, if the connection fails, it should be logged in the add-on log page

**Comment by stevenengland** [comment]
Hi @mib1185 when activating verification errors are present, yes:

```
[08:52:23] INFO: Set configuration...
[08:52:24] INFO: Starting the daemon...
Traceback (most recent call last):
  File "/journal2syslog.py", line 149, in <module>
    syslog_handler = TlsSysLogHandler(
                     ^^^^^^^^^^^^^^^^^
  File "/journal2syslog.py", line 52, in __init__
    super().__init__(address, facility, socktype)
  File "/usr/lib/python3.11/logging/handlers.py", line 867, in __init__
    self.createSocket()
  File "/journal2syslog.py", line 107, in createSocket
    raise err
  File "/journal2syslog.py", line 100, in createSocket
    sock.connect(sa)
  File "/usr/lib/python3.11/ssl.py", line 1412, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.11/ssl.py", line 1403, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:992)
s6-rc: info: service legacy-services: stopping
```

**Comment by mib1185** [comment]
ok, this proofs, that the connection to your syslog server is proper established, just the SSL handshake fails in this case. You can disable the verification again.

Which syslog server do you use?

**Comment by stevenengland** [comment]
I use graylog for that job. But I do not see any error messages on that host machine.

**Comment by mib1185** [comment]
as your test in https://github.com/mib1185/ha-addon-syslog/issues/8#issuecomment-2351418246 proofs, that the tls connection itself seems to be established (_you can also check it by sniffing the traffic on the Graylog server or maybe there is a proper logfile_) and i'm not familiar with Graylog, but I think there is something wrong in its [tls syslog input settings](https://go2docs.graylog.org/current/getting_in_log_data/syslog_inputs.html) :thinking: Did you use the correct port (_do not use the https port of the web interface_)

**Comment by stevenengland** [comment]
Hi @mib1185, the TLS setup of Graylog is in use by a lot of other hosts. That shouldn't be a problem. Maybe within this week I will have a bit of time to look for further logs etc.
